### ISSUE TITLE
Possibility of using rclone in place of rsync?

### ISSUE THREAD

**Issue by novosirj** [hjmangalam/parsyncfp2#3]
We have mostly stopped using parsyncfp (we haven't yet used version 2, for example) because we've switched mostly to cloud storage, which does not support rsync. We can connect to them with rclone (https://rclone.org), however, which is really similar as far as the command line, etc. goes. Do you imagine this would be possible?

**Comment by hjmangalam** [comment]
It would be clearly be possible but it would require some reworking to
support and check all the options, etc.
I'm currently building a house, so I can't do anything before that. I can
look at anything before December.

I seem to remember that rclone uses a parallel approach anyway tho . Is
that not the case?

Harry

**Comment by hjmangalam** [comment]
The use of rclone and other transport mechanisms (netcat, UDR, etc)  using pfp2's multiple spawn approach is on my TODO list, but far enough out that I'm not going to keep the issue open for now.
